### ISSUE TITLE
Als bezoeker van de Red Pers-website wil ik een contactformulier gebruiken zodat ik eenvoudig contact kan opnemen met de juiste redactieleden

### ISSUE THREAD

**Issue by fatimahilali** [fatimahilali/the-client-website#125]
![Image](https://github.com/user-attachments/assets/2b03b5f9-a54f-419e-a282-766b666e9ed9)
![Image](https://github.com/user-attachments/assets/c18a5144-a8b0-457a-8ac2-adc3c46f8fb0)
![Image](https://github.com/user-attachments/assets/0148dffe-0958-4796-b941-eb3ca78a080d)
![Image](https://github.com/user-attachments/assets/2ef80e62-1fe3-4a32-80a1-e46c1be240e8)
![Image](https://github.com/user-attachments/assets/6fe662c5-8aaf-4a0c-b027-dfe2ff028f73)
![Image](https://github.com/user-attachments/assets/929412c0-d875-4a60-b12e-4f05102ae9db)

**Comment by fatimahilali** [comment]
Deze issue kan worden gesloten, omdat de opdracht is voltooid.

**Comment by fatimahilali** [comment]
@Krijnhoetmer @koopreynders
Hoi,
Zou ik graag feedback kunnen krijgen op mijn wireflow voor de contactpagina. Aangezien ik niet kan schetsen, heb ik het in Figma gemaakt. Alvast bedankt! :)

**Comment by KoopReynders** [comment]
Mooi uitgewerkt en beschreven. 
De form validate kan client-side voor een deel heel mooi met CSS. 
Voor de micro interactie kan je misschien nog iets verzinnen voor feedback als een gebruiker op de knop heeft geklikt? Dan heb je javascript nodig!

Kun je de interactie met feedback als de gebruiker op de button klikt ook in de style van de website uitwerken? bv in Figma? Als je al een high fidelity ontwerp hebt kan je dat ook gebruiken voor een wireflow, dan wordt het een screenflow!

**Comment by fatimahilali** [comment]
@KoopReynders 
Bedankt voor de feedback! Ik ga ermee aan de slag en zal de interacties en stijl verder uitwerken.

**Comment by fatimahilali** [comment]
Deze issue kan gesloten worden, de feedback is verwerkt.
